plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.ondeviceai'
version = '1.0.0'

android {
  namespace "expo.modules.ondeviceai"
  defaultConfig {
    versionCode 1
    versionName '1.0.0'
  }
}

dependencies {
  implementation 'com.google.mlkit:genai-prompt:1.0.0-beta2'
  implementation 'com.google.mlkit:translate:17.0.3'
  implementation 'com.google.mlkit:language-id:17.0.6'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2'
}
